openapi: 3.0.0
info:
  title: Arbitrage Services API
  version: 0.1.0

servers:
  - url: https://185.240.103.242:50051

paths:
  /signup:
    post:
      summary: Регистрация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  required: true
                password:
                  type: string
                  required: true
                name:
                  type: string
                  required: true
                telegram:
                  type: string
                  required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string

        '400':
          description: Required parameter is missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

        '408':
          description: User already exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

  /login:
    post:
      summary: Вход в аккаунт
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  required: true
                password:
                  type: string
                  required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                  user_info:
                    $ref: '#/components/schemas/user_info'

        '400':
          description: Required parameter is missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

        '402':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

        '403':
          description: Wrong password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

  /logout:
    post:
      summary: Выход
      security:
        - bearer_auth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

        '401':
          description: Authorization invalids
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

  /refresh:
    post:
      summary: Обновление refresh_token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
                  required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success

        '400':
          description: Required parameter is missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

        '404':
          description: Wrong refresh token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

  /info:
    get:
      summary: Получение информации о пользователе
      security:
        - bearer_auth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_info:
                    $ref: '#/components/schemas/user_info'

        '401':
          description: Authorization invalids
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

        '402':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

        '405':
          description: Invalid signature
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

        '406':
          description: Token expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

    post:
      summary: Изменение параметров пользователя
      security:
        - bearer_auth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_info'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

        '401':
          description: Authorization invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

        '402':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

        '405':
          description: Invalid signature
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

        '406':
          description: Token expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

        '407':
          description: Invalid parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

  /pay:
    post:
      summary: Оплата
      security:
        - bearer_auth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                payment_amount:
                  type: string
                  required: true
                  description: Сумма оплаты
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  link:
                    type: string
                    description: Ссылка для оплаты

        '400':
          description: Required parameter is missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

        '401':
          description: Authorization invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

        '407':
          description: Invalid parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

  /password/recover:
    get:
      summary: Восстановление пароля
      parameters:
        - name: email
          in: query
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

        '401':
          description: Authorization invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

        '402':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

    post:
      summary: Проверка кода
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
        '400':
          description: Required parameter is missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
        '407':
          description: Code is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

  /password/change:
    post:
      summary: Изменение пароля
      security:
        - bearer_auth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
        '400':
          description: Required parameter is missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
        '401':
          description: Authorization invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

  /notifications:
    get:
      summary: Получение уведомлений пользователя
      security:
        - bearer_auth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/notification'

        '401':
          description: Authorization invalids
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

    post:
      summary: Отметить уведомление прочитанным
      security:
        - bearer_auth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  required: true
                  description: id уведомления

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

        '400':
          description: Required parameter is missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

        '401':
          description: Authorization invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

  /general/videos:
    get:
      summary: Ссылки на видео для блока на главной странице
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  videos:
                    type: array
                    items:
                      type: object
                      properties:
                        link:
                          type: string
                        image:
                          type: string
                          description: Путь к картинке

  /general/markets:
    get:
      summary: Список бирж и их названия
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  markets:
                    type: array
                    items:
                      type: object
                      properties:
                        market:
                          type: string
                          description: Системное название, например, "gateio"
                        name:
                          type: string
                          description: Название биржи, например "Gate.io"

components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    user_info:
      type: object
      properties:
        name:
          type: string
          description: Имя пользователя
        telegram:
          type: integer
          description: Телеграм
        email:
          type: string
          description: Почта
        page:
          type: integer
          description: Страница, на которой находится пользователь (нумерация с нуля)
        max_pages:
          type: integer
          description: Всего страниц для пользователя
        monitoring:
          type: integer
          description: 0 - не присылать уведомления, 1 - присылать
        profit_spread:
          type: string
          description: Спред в долларах
        percent_spread:
          type: string
          description: Спред в процентах
        fee:
          type: string
          description: Максимальная комиссия
        hedge_type:
          type: integer
          description: 0 - любые монеты, 1 - только хедж
        risk_type:
          type: integer
          description: 0 - безопасный режим, 1 - рискованный
        volume_min:
          type: string
          description: Минимальный объем
        volume_max:
          type: string
          description: Максимальный объем
        markets_buy:
          type: array
          items:
            type: string
          description: Биржи покупки
        markets_sell:
          type: array
          items:
            type: string
          description: Биржи продажи
        monets:
          type: array
          items:
            type: string
          description: Монеты в ЧС
        chains:
          type: array
          items:
            type: string
          description: Сети в ЧС
        end_date:
          type: string
          description: Дата окончания подписки

    notification:
      type: object
      properties:
        id:
          type: integer
          description: id уведомления
          required: true
        title:
          type: string
          description: Заголовок
          required: true
        content:
          type: string
          description: Содержание
          required: true
        creation_date:
          type: string
          description: Время создания. Например, "Tue, 13 Jun 2023 21:36:05 GMT"
          required: true
        if_read:
          type: boolean
          description: Прочитано ли уведомление
          required: true

    error_message:
      type: object
      properties:
        message:
          type: string
          description: Описание ошибки
